#!/usr/bin/python3

# ==============================================================================
#
#     ANNarchyProfiler.py
#
#     This file is part of ANNarchyProfiler.
#
#     Copyright (C) 2021  Max Linke <max.linke@live.de>
#
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     ANNarchyProfiler is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# ==============================================================================

import sys

from PyQt5 import QtWidgets

from ANNarchyProfiler import ANNarchyProfiler

"""
ANNarchyProfiler is a side project to the ANNarchy neuro simulator framework.
Its purpose is to analyse xml files generated by ANNarchy which contain performance
information.

This branch is a total rework of the master branch as the project lacks proper
documentation and is practically not maintainable.

Start the script with:
    $ ./main.py

If you wish to overwrite the shebang, use:
    $ python3 main.py

This tool is on GitHub: https://github.com/hdinkelbach/ANNarchyProfiler
"""


def main():
    app = QtWidgets.QApplication(sys.argv)
    window = ANNarchyProfiler()
    window.show()
    sys.exit(app.exec_())


if __name__ == "__main__":
    main()